DROP TABLE REPORT_MEM_INFO;
DROP TABLE REPORT_MY_HISTORY;
DROP TABLE REPORT_TASK;

COMMIT;

SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'REPORT_%';


-- 시퀀스 제거
DROP SEQUENCE REPORT_MEM_INFO_SEQ;
DROP SEQUENCE REPORT_MY_HISTORY_SEQ;
DROP SEQUENCE REPORT_TASK_SEQ;


-- 시퀀스 추가
CREATE SEQUENCE REPORT_MEM_INFO_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE REPORT_MY_HISTORY_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE REPORT_TASK_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE NOCYCLE NOCACHE NOORDER;