INSERT INTO REPORT_MEM_INFO ( MEM_SEQ, MEM_NAME, MEM_TEL, MEM_IMG, MEM_ADDR, CREATE_DATE )
  VALUES 
(REPORT_MEM_INFO_SEQ.NEXTVAL, '김가람', '010-1234-5678', '', '서울', TO_CHAR(SYSDATE, 'YYYY-MM-DD'));

INSERT INTO REPORT_MEM_INFO ( MEM_SEQ, MEM_NAME, MEM_TEL, MEM_IMG, MEM_ADDR, CREATE_DATE )
  VALUES 
(REPORT_MEM_INFO_SEQ.NEXTVAL, '봄날에', '010-1234-5678', '', '서울', TO_CHAR(SYSDATE, 'YYYY-MM-DD'));

INSERT INTO REPORT_MEM_INFO ( MEM_SEQ, MEM_NAME, MEM_TEL, MEM_IMG, MEM_ADDR, CREATE_DATE )
  VALUES 
(REPORT_MEM_INFO_SEQ.NEXTVAL, '초코파이', '010-1234-5678', '', '청주', TO_CHAR(SYSDATE, 'YYYY-MM-DD'));

INSERT INTO REPORT_MEM_INFO ( MEM_SEQ, MEM_NAME, MEM_TEL, MEM_IMG, MEM_ADDR, CREATE_DATE )
  VALUES 
(REPORT_MEM_INFO_SEQ.NEXTVAL, '빅맥', '010-1234-5678', '', '강릉', TO_CHAR(SYSDATE, 'YYYY-MM-DD'));

INSERT INTO REPORT_MEM_INFO ( MEM_SEQ, MEM_NAME, MEM_TEL, MEM_IMG, MEM_ADDR, CREATE_DATE )
  VALUES 
(REPORT_MEM_INFO_SEQ.NEXTVAL, '하하하', '010-1234-5678', '', '제주', TO_CHAR(SYSDATE, 'YYYY-MM-DD'));

INSERT INTO REPORT_MEM_INFO ( MEM_SEQ, MEM_NAME, MEM_TEL, MEM_IMG, MEM_ADDR, CREATE_DATE )
  VALUES 
(REPORT_MEM_INFO_SEQ.NEXTVAL, '제임스', '010-1234-5678', '', '강원', TO_CHAR(SYSDATE, 'YYYY-MM-DD'));


DROP TABLE REPORT_MEM_INFO;
DROP TABLE REPORT_MY_HISTORY;
DROP TABLE REPORT_TASK;

SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'REPORT_%';

SELECT * FROM REPORT_MEM_INFO;

-- 회원정보 관련

-- 회원이력 관련
SELECT * FROM REPORT_MY_HISTORY;



INSERT INTO REPORT_MY_HISTORY
        ( HISTORY_SEQ, MEM_SEQ, COMPANY_NAME, COMPANY_TEL, FROM_TO, CREATE_DATE ) VALUES
        ( REPORT_MY_HISTORY_SEQ.NEXTVAL, 
        1, '좋은회사', '02-1234-5678', '2000-12-12 ~ 2020-12-12', TO_CHAR(SYSDATE, 'YYYY-MM-DD'));
COMMIT;


SELECT * FROM REPORT_MY_HISTORY;
ROLLBACK;


SELECT * FROM REPORT_TASK;

UPDATE REPORT_MEM_INFO         SET             
TASK_DETAIL = '?'           
, LINK_URL = '?'           
, ADD_FILE = '?'           
, HISTORY_SEQ = 1         
WHERE TASK_SEQ = 1;